; debug ini
[ODBC_INFO]
ODBC_TYPE= "DSN={0};Uid={1};Pwd={2};"
ODBC_USER= "sa"
ODBC_PASSWORD= "sa@1q2w3e4r5t"
ODBC_NAME= "DTS"
ODBC_DATABASE_NAME= "DTS"

[SERVER_INFO]
SERVER_NAME= "DLT-01"
SERVER_IP= "172.16.0.5"

[DATABASE]
CONNECTIONSTRING = "Data Source=DLT-01;Initial Catalog=DTS;User ID=sa;Password=sa@1q2w3e4r5t;TrustServerCertificate=True;"

[API_AUTH]
USERNAME= "root"
PASSWORD= "Root@@Kai200222"
TOKEN= "@ETPNqq*9$GD+e9lyqrUa$M4#dG$^wtF"
